"""add_is_admin_and_new_models

Revision ID: 4df78ac76311
Revises: 
Create Date: 2026-02-25 22:45:50.344282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df78ac76311'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('cefr_level', sa.String(length=5), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('examples_json', sa.JSON(), nullable=True),
    sa.Column('tips_json', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_topics_category'), 'grammar_topics', ['category'], unique=False)
    op.create_table('textbook_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('publisher', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.String(length=10), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_notebook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('question_snapshot', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_notebook_entries_source_type'), 'error_notebook_entries', ['source_type'], unique=False)
    op.create_index(op.f('ix_error_notebook_entries_status'), 'error_notebook_entries', ['status'], unique=False)
    op.create_index(op.f('ix_error_notebook_entries_user_id'), 'error_notebook_entries', ['user_id'], unique=False)
    op.create_table('grammar_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('answer', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('exercise_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['grammar_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_exercises_topic_id'), 'grammar_exercises', ['topic_id'], unique=False)
    op.create_table('learning_time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_time_logs_date'), 'learning_time_logs', ['date'], unique=False)
    op.create_index(op.f('ix_learning_time_logs_module'), 'learning_time_logs', ['module'], unique=False)
    op.create_index(op.f('ix_learning_time_logs_user_id'), 'learning_time_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('onboarding_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assessment_score', sa.Integer(), nullable=True),
    sa.Column('assessment_result_json', sa.JSON(), nullable=True),
    sa.Column('recommended_path', sa.String(length=50), nullable=True),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('target_exam', sa.String(length=50), nullable=True),
    sa.Column('completed_steps_json', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_profiles_user_id'), 'onboarding_profiles', ['user_id'], unique=True)
    op.create_table('textbook_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('vocabulary_json', sa.JSON(), nullable=True),
    sa.Column('grammar_points_json', sa.JSON(), nullable=True),
    sa.Column('key_sentences_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbook_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_textbook_units_textbook_id'), 'textbook_units', ['textbook_id'], unique=False)
    op.create_table('user_grammar_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['grammar_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_grammar_progress_topic_id'), 'user_grammar_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_grammar_progress_user_id'), 'user_grammar_progress', ['user_id'], unique=False)
    op.create_table('user_textbook_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Integer(), nullable=False),
    sa.Column('current_unit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_unit_id'], ['textbook_units.id'], ),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbook_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_textbook_settings_user_id'), 'user_textbook_settings', ['user_id'], unique=True)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_user_textbook_settings_user_id'), table_name='user_textbook_settings')
    op.drop_table('user_textbook_settings')
    op.drop_index(op.f('ix_user_grammar_progress_user_id'), table_name='user_grammar_progress')
    op.drop_index(op.f('ix_user_grammar_progress_topic_id'), table_name='user_grammar_progress')
    op.drop_table('user_grammar_progress')
    op.drop_index(op.f('ix_textbook_units_textbook_id'), table_name='textbook_units')
    op.drop_table('textbook_units')
    op.drop_index(op.f('ix_onboarding_profiles_user_id'), table_name='onboarding_profiles')
    op.drop_table('onboarding_profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_learning_time_logs_user_id'), table_name='learning_time_logs')
    op.drop_index(op.f('ix_learning_time_logs_module'), table_name='learning_time_logs')
    op.drop_index(op.f('ix_learning_time_logs_date'), table_name='learning_time_logs')
    op.drop_table('learning_time_logs')
    op.drop_index(op.f('ix_grammar_exercises_topic_id'), table_name='grammar_exercises')
    op.drop_table('grammar_exercises')
    op.drop_index(op.f('ix_error_notebook_entries_user_id'), table_name='error_notebook_entries')
    op.drop_index(op.f('ix_error_notebook_entries_status'), table_name='error_notebook_entries')
    op.drop_index(op.f('ix_error_notebook_entries_source_type'), table_name='error_notebook_entries')
    op.drop_table('error_notebook_entries')
    op.drop_table('textbook_versions')
    op.drop_index(op.f('ix_grammar_topics_category'), table_name='grammar_topics')
    op.drop_table('grammar_topics')
    # ### end Alembic commands ###
