"""add_question_analyses_table

Revision ID: 5cf2aaa16a59
Revises: 4df78ac76311
Create Date: 2026-02-27 14:15:17.440324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf2aaa16a59'
down_revision: Union[str, None] = '4df78ac76311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('key_phrases_json', sa.Text(), nullable=True),
    sa.Column('reading_order_json', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('distractors_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_analyses_question_hash'), 'question_analyses', ['question_hash'], unique=True)
    op.create_index(op.f('ix_question_analyses_question_id'), 'question_analyses', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_analyses_question_id'), table_name='question_analyses')
    op.drop_index(op.f('ix_question_analyses_question_hash'), table_name='question_analyses')
    op.drop_table('question_analyses')
    # ### end Alembic commands ###
