"""add question_eye_json to question_analyses

Revision ID: 84da144db47a
Revises: b4802f9c3d67
Create Date: 2026-02-27 20:26:11.199187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84da144db47a'
down_revision: Union[str, None] = 'b4802f9c3d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_analyses', sa.Column('question_eye_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_analyses', 'question_eye_json')
    # ### end Alembic commands ###
