"""v2_gaze_path_and_human_annotations

Revision ID: d2506e927182
Revises: 5cf2aaa16a59
Create Date: 2026-02-27 15:33:57.490967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2506e927182'
down_revision: Union[str, None] = '5cf2aaa16a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotator_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('gaze_path_json', sa.Text(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_annotations_annotator_id'), 'human_annotations', ['annotator_id'], unique=False)
    op.create_index(op.f('ix_human_annotations_question_id'), 'human_annotations', ['question_id'], unique=False)
    op.add_column('question_analyses', sa.Column('gaze_path_json', sa.Text(), nullable=True))
    op.add_column('question_analyses', sa.Column('narration', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_analyses', 'narration')
    op.drop_column('question_analyses', 'gaze_path_json')
    op.drop_index(op.f('ix_human_annotations_question_id'), table_name='human_annotations')
    op.drop_index(op.f('ix_human_annotations_annotator_id'), table_name='human_annotations')
    op.drop_table('human_annotations')
    # ### end Alembic commands ###
