/** Theme CSS variable definitions for 6 themes */
export const themeVariables: Record<string, Record<string, string>> = {
  ocean: {
    "--color-primary": "#3b82f6",
    "--color-primary-light": "#dbeafe",
    "--color-primary-dark": "#1d4ed8",
    "--color-accent": "#06b6d4",
    "--color-primary-rgb": "59, 130, 246",
    "--color-accent-rgb": "6, 182, 212",
    "--color-bg": "#f0f9ff",
    "--color-surface": "#ffffff",
    "--color-surface-hover": "#f0f9ff",
    "--color-sidebar": "#ffffff",
    "--color-text": "#1e293b",
    "--color-text-secondary": "#64748b",
    "--color-border": "#e2e8f0",
  },
  forest: {
    "--color-primary": "#22c55e",
    "--color-primary-light": "#dcfce7",
    "--color-primary-dark": "#15803d",
    "--color-accent": "#84cc16",
    "--color-primary-rgb": "34, 197, 94",
    "--color-accent-rgb": "132, 204, 22",
    "--color-bg": "#f0fdf4",
    "--color-surface": "#ffffff",
    "--color-surface-hover": "#f0fdf4",
    "--color-sidebar": "#ffffff",
    "--color-text": "#1a2e1a",
    "--color-text-secondary": "#4b6b4b",
    "--color-border": "#d1e7d1",
  },
  sunset: {
    "--color-primary": "#f97316",
    "--color-primary-light": "#fff7ed",
    "--color-primary-dark": "#c2410c",
    "--color-accent": "#eab308",
    "--color-primary-rgb": "249, 115, 22",
    "--color-accent-rgb": "234, 179, 8",
    "--color-bg": "#fffbeb",
    "--color-surface": "#ffffff",
    "--color-surface-hover": "#fff7ed",
    "--color-sidebar": "#ffffff",
    "--color-text": "#292524",
    "--color-text-secondary": "#78716c",
    "--color-border": "#e7e5e4",
  },
  lavender: {
    "--color-primary": "#a78bfa",
    "--color-primary-light": "#ede9fe",
    "--color-primary-dark": "#7c3aed",
    "--color-accent": "#c084fc",
    "--color-primary-rgb": "167, 139, 250",
    "--color-accent-rgb": "192, 132, 252",
    "--color-bg": "#faf5ff",
    "--color-surface": "#ffffff",
    "--color-surface-hover": "#faf5ff",
    "--color-sidebar": "#ffffff",
    "--color-text": "#1e1b2e",
    "--color-text-secondary": "#6b6b8a",
    "--color-border": "#e2dff0",
  },
  midnight: {
    "--color-primary": "#6366f1",
    "--color-primary-light": "#1e1b4b",
    "--color-primary-dark": "#4338ca",
    "--color-accent": "#818cf8",
    "--color-primary-rgb": "99, 102, 241",
    "--color-accent-rgb": "129, 140, 248",
    "--color-bg": "#0f0f23",
    "--color-surface": "#1a1a2e",
    "--color-surface-hover": "#25254a",
    "--color-sidebar": "#16162b",
    "--color-text": "#e2e8f0",
    "--color-text-secondary": "#94a3b8",
    "--color-border": "#2d2d5e",
  },
  sakura: {
    "--color-primary": "#ec4899",
    "--color-primary-light": "#fce7f3",
    "--color-primary-dark": "#be185d",
    "--color-accent": "#f472b6",
    "--color-primary-rgb": "236, 72, 153",
    "--color-accent-rgb": "244, 114, 182",
    "--color-bg": "#fdf2f8",
    "--color-surface": "#ffffff",
    "--color-surface-hover": "#fdf2f8",
    "--color-sidebar": "#ffffff",
    "--color-text": "#2e1a24",
    "--color-text-secondary": "#8a6b7a",
    "--color-border": "#f0d1e0",
  },
};
